name: omnis
description: P2P Messenger

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  server:
    path: server

  domain:
    path: domain

  data:
    path: data

  common:
    path: common

  services:
    path: services

  #Notifications
  flutter_local_notifications: ^9.7.0

  # Localization
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  # Icons
  cupertino_icons: ^1.0.2
  flutter_iconly: ^1.0.2

  # Utils
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.5+1
  worker_manager: ^4.3.5
  collection: ^1.16.0
  permission_handler: ^10.0.0
  record: ^4.3.1
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  flutter_background_service: ^2.1.3
  flutter_native_splash: ^2.2.4
  logger: ^1.1.0
  dartz: ^0.10.1
  visibility_detector: ^0.3.3
  file_picker: ^4.6.1
  image_size_getter: ^2.1.2

  # Routing
  auto_route: ^4.2.1

  # State Management
  flutter_bloc: ^8.0.1
  side_effect_bloc: ^1.0.0
  rxdart: ^0.27.4
  bloc_concurrency: ^0.2.0
  mobx: ^2.0.7+4
  mobx_codegen: ^2.0.7
  flutter_mobx: ^2.0.6+1

  # DI
  injectable: ^1.5.3
  get_it: ^7.2.0

  # UI
  qr_flutter: ^4.0.0
  flutter_spinkit: ^5.1.0
  modal_bottom_sheet: ^2.1.0

  just_audio: ^0.9.28

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Routing
  auto_route_generator: ^4.2.0

  # DI
  injectable_generator: ^1.5.3

  # Linter
  flutter_lints: ^2.0.0

  # Codegen
  build_runner: ^2.1.11

  # Utils
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true