publish_to: none
name: services
description: Services for Omnis
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common

  server:
    path: ../server

  domain:
    path: ../domain

  #Notifications
  flutter_local_notifications: ^9.7.0

  # Utils
  permission_handler: ^10.0.0
  record: ^4.3.1
  path_provider: ^2.0.11
  flutter_background_service: ^2.1.3
  path:

  # DI
  injectable: ^1.5.3
  get_it: ^7.2.0

  just_audio: ^0.9.28

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # DI
  injectable_generator: ^1.5.3

  # Codegen
  build_runner: ^2.1.11

flutter:

module:
  androidX: true
  androidPackage: space.sproject.omnis.services
  iosBundleIdentifier: space.sproject.omnis.services