publish_to: none
name: server
description: Server for Omins
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  data:
    path: ../data

  common:
    path: ../common

  # DI
  injectable: ^1.5.3
  get_it: ^7.2.0

  # HTTP
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.2

  # Encryption
  crypton: ^2.0.5
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # DI
  injectable_generator: ^1.5.3

  # Codegen
  build_runner: ^2.1.11

flutter:

module:
  androidX: true
  androidPackage: space.sproject.omnis.server
  iosBundleIdentifier: space.sproject.omnis.server