publish_to: none
name: common
description: Common layer for Omnis
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  # Network
  network_info_plus: ^2.1.3

  # Encryption
  crypton: ^2.0.5
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

module:
  androidX: true
  androidPackage: space.sproject.omnis.common
  iosBundleIdentifier: space.sproject.omnis.common
